# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


# The basic colors
foreground              #cdd6f4
background              #000
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Scrollbar colors
scrollbar_handle_color  #9399b2
scrollbar_track_color   #45475a

# URL color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #222222
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #111
color8 #111

# red
color1 #f9b
color9 #f9b

# green
color2  #3fe
color10 #3fe

# yellow
# color3  #f9e2af
color3 #edc
color11 #f9e2af

# blue

color4  #6bf
color12 #6bf

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

# Font settings
font_family family="JetBrainsMono Nerd Font" style=Light
bold_font family="JetBrainsMono Nerd Font" style=Medium
italic_font auto
bold_italic_font auto
font_size 15.0
adjust_line_height 100%
font_features JetBrainsMonoNerd +liga +calt

# Cursor
cursor #77f
cursor_shape underline
cursor_blink_interval 0.3
cursor_shape_unfocused hollow

# Cursor Trail
cursor_trail 1
cursor_trail_decay 0.02 0.15
cursor_trail_start_threshold 1
cursor_trail_color #0de

# Theme - currently unused
# include current-theme.conf


map f6 launch --allow-remote-control kitty +kitten broadcast


allow_remote_control yes
